### ISSUE TITLE
How to use commond StrCompx and logx??

### ISSUE THREAD

**Issue by mebuis** [Ahmadmansoor/AdvancedScript#10]
hello,Ahmadmansoor！！
I'm very sorry, but my code ability is very poor。how to use Undocumented command?
like StrCompx or logx and so on.
And How to use AdvancedScript set the condition bp of string like OD
bp CreateFileW,[UNICODE[esp+4]]=="C:\\test.exe"

**Comment by Ahmadmansoor** [comment]
I don't know what is wrong to understand StrCompx or logx commands, they are already clear in help.
just check LogxTemplateManager first to make ur template to log it.
u can use this at BP dialog:
StrCompx 0,template1,{[esp+4]},C:\test.exe
don't forget to define template1 in LogxTemplateManager .

**Comment by mebuis** [comment]
Thanks for your answer! I like this plugin very much and thank you for your help!!
