### ISSUE TITLE
How To Use Script Editor?

### ISSUE THREAD

**Issue by cryzlasm** [Ahmadmansoor/AdvancedScript#4]
![image](https://user-images.githubusercontent.com/20424580/59989860-5169de00-9630-11e9-95c4-c3a13cb7566e.png)

![image](https://user-images.githubusercontent.com/20424580/59989866-5c247300-9630-11e9-8569-f4883d04ef1b.png)

**Comment by cryzlasm** [comment]
I Found It

![image](https://user-images.githubusercontent.com/20424580/59989953-cb01cc00-9630-11e9-845f-7fab622d64e4.png)


![image](https://user-images.githubusercontent.com/20424580/59989973-e53baa00-9630-11e9-92bb-56a047b2ed22.png)

**Comment by cryzlasm** [comment]
OpenScript  -> cancel  -> Exception



![image](https://user-images.githubusercontent.com/20424580/59990049-32b81700-9631-11e9-9b43-3bab8aa036c6.png)

**Comment by Ahmadmansoor** [comment]
Lol I forget to add this Line:
if (openFileDialog1->ShowDialog() == Windows::Forms::DialogResult::OK) 
it fixes now with the new update, today upload it :)
Thanks for support
I will add more youtube and more tut's on how to use it
